### ISSUE TITLE
cli option `--root` is broken

### ISSUE THREAD

**Issue by mgreter** [sass/sass-spec#1025]
Steps to reproduce:
```sh
git clone https://github.com/sass/sass-spec.git spec1
git clone https://github.com/sass/sass-spec.git spec2
ruby spec1/sass-spec.rb -r spec2/spec
```

Results in:
```
Test case ... is not within the spec directory spec1/spec
```

I suspect https://github.com/sass/sass-spec/blob/master/lib/sass_spec/test_case_metadata.rb#L42, since it does not seem to respect `options[:spec_directory]`, but I failed to come up with something workable.

**Comment by nex3** [comment]
Closing this out since we've deprecated the Sass runner anyway.
