### ISSUE TITLE
Add Contributing.md

### ISSUE THREAD

**Issue by nschonni** [sass/sass-spec#1036]
This was previously discussed in #9, but the links to the Wiki no longer exist. 
- [ ] Where to put the test(s)
- [ ] When to mark implementations TODO/Ignored

**Comment by nschonni** [comment]
@nex3 do you think that "STYLE_GUIDE.md" covers this off? Or should a Contributing.md also be added?

**Comment by nex3** [comment]
I think the style guide covers this sufficiently.
