### ISSUE TITLE
Reporting results fails due to Encoding::CompatibilityError

### ISSUE THREAD

**Issue by kaj** [sass/sass-spec#1062]
I try to run `sass-spec.rb` to test my own sass implementation https://github.com/kaj/rsass .  Since it is a rather new project, it fails most of the tests, but running the full suite `sass-spec.rb` fails to report the number of successes / failures, giving instead a stack trace like this:

```
Finished in 1.730533s, 804.9545 runs/s, 47.9621 assertions/s.
/home/kaj/.gem/ruby/gems/minitest-5.8.3/lib/minitest.rb:583:in `join': incompatible character encodings: ASCII-8BIT and UTF-8 (Encoding::CompatibilityError)
	from /home/kaj/.gem/ruby/gems/minitest-5.8.3/lib/minitest.rb:583:in `aggregated_results'
	from /home/kaj/.gem/ruby/gems/minitest-5.8.3/lib/minitest.rb:568:in `report'
	from /home/kaj/.gem/ruby/gems/minitest-5.8.3/lib/minitest.rb:640:in `each'
	from /home/kaj/.gem/ruby/gems/minitest-5.8.3/lib/minitest.rb:640:in `report'
	from /home/kaj/.gem/ruby/gems/minitest-5.8.3/lib/minitest.rb:134:in `run'
	from /home/kaj/proj/rust/sassers/sass-spec/lib/sass_spec/runner.rb:45:in `run'
	from ./sass-spec.rb:45:in `<main>'
```

Instructions to reproduce, requires Rust language toolchain:

```sh
git clone https://github.com/kaj/rsass
cd rsass && cargo build
cd ../sass-spec
./sass-spec.rb -c ../rsass/target/debug/rsass  --impl rsass spec/output_styles/compressed/libsass/
```

The path `spec/output_styles/compressed` is as specific as I have managed to find the error (but there are several other paths that also triggers it).  Note that none of the test inside that directory triggers the test by themself.

**Comment by kaj** [comment]
I found a rather simple workaround.  Setting the `LANG` to `C` (as opposed to anything that mentions UTF8, such as my normal `LANG=sv_SE.utf8`).

**Comment by nex3** [comment]
This looks like a configuration issue on your end, but I'm not up on my Ruby encoding nonsense enough to figure out exactly why it would be happening. My best guess is that your `Encoding.default_internal` is set to ASCII for some reason, but I'm not sure exactly how that's set by default.
