### ISSUE TITLE
Make static property specs non-canonical

### ISSUE THREAD

**Issue by nex3** [sass/sass-spec#1075]
Ruby Sass parses simple properties—that is, those that match a certain regular expression—as "static", meaning that it treats them as plain strings rather than full expressions. This is purely for parsing efficiency, and isn't necessary for implementations in faster languages with better parsers.

The canonical specs currently reflect the static parsing, since they were originally tied closely to Ruby Sass's output. But now that Dart Sass exists and Ruby Sass is being phased out, there's no reason to test against the static properties. We should make the non-static versions canonical, and add Ruby Sass-specific outputs for the static properties.

**Comment by stof** [comment]
@nex3 now that ruby-sass specific outputs have been removed, is there still anything left to do here, or are those static property specs already gone ?

**Comment by nex3** [comment]
Hmm, there are still some specs that don't treat Dart Sass's output as canonical, but I'm not sure if they're because of static property parsing. Either way, this should be merged with #1074.
