### ISSUE TITLE
GitHub Readable spec format

### ISSUE THREAD

**Issue by nschonni** [sass/sass-spec#1095]
This popped into my head so I figure I'd share it to see if made sense to anyone else. If Markdown files are used for the specs, then we would have a readable spec for people right on GitHub, it could then also easily be converted to a GH Pages site.
Here is a random set of specs I tried to pull into a prospective format https://gist.github.com/nschonni/44dad08ad6e6c9f26cec26200928f4fd

Could also add the metadata for linking the related GH issues too

**Comment by stof** [comment]
@nex3 should this be closed now that HRX is used ?

**Comment by saper** [comment]
@stof er, somewhat, but it's probably personal taste. I [don't know a lot about decisions behind the design](https://github.com/sass/sass-spec/pull/1484#issuecomment-567709171) of the HRX format, beyond it's [general goals](https://github.com/google/hrx/blob/870b087606f270096a083bbbf2bfd64409876d98/README.md#goals).

**Comment by nex3** [comment]
I think this can be closed out. We're not planning on changing the spec format further, beyond changes to the HRX spec itself.
