### ISSUE TITLE
Figure out how to handle libsass and 3.4 specs

### ISSUE THREAD

**Issue by nex3** [sass/sass-spec#1168]
[The Travis build](https://travis-ci.org/sass/sass-spec/jobs/281486110) running against libsass's 3.4-stable is failing as of #1167. This is expected, since that pull request removes all the 3.4-specific annotations and marks 3.5 as the lowest version, which doesn't necessarily match 3.4-stable's functionality.

I'm not sure what the right solution is, though. @xzyfer, can you look into this and figure out if a new libsass stable branch needs to be cut from master or whatever?

**Comment by nex3** [comment]
@xzyfer Has this been resolved?

**Comment by xzyfer** [comment]
Yes.
