### ISSUE TITLE
Error running "bundle install"

### ISSUE THREAD

**Issue by mgreter** [sass/sass-spec#1204]
Getting the following error on windows 10 and gentoo linux running `bundle install`:

```
[!] There was an error parsing `Gemfile`: There was a ArgumentError while loading sass-spec.gemspec:
invalid byte sequence in US-ASCII from
  /home/mgreter/sass-spec/sass-spec.gemspec:23:in `split'
. Bundler cannot continue.

 #  from /home/mgreter/sass-spec/Gemfile:3
 #  -------------------------------------------
 #
 >  gemspec
 #
 #  -------------------------------------------
```

Seems due to `split("\x0")` in `sass-spec.gemspec` 😞

**Comment by lunelson** [comment]
Same here on macos 10.13.6

**Comment by nex3** [comment]
@lunelson Are you getting the same error message as Marcel, or a different one?

There's really no reason to have a gemspec at all once Ruby Sass is turned down... I think the easiest solution here is to just wait a week until Ruby Sass expires and then delete the gemspec entirely.

**Comment by lunelson** [comment]
@nex3 I was getting an error on the same line yeah. OK, hmmm which files/lines would I have to delete in order to skip the gemspec stuff? I can also wait a week of course.

**Comment by nex3** [comment]
If you delete the `spec.files` line it should work fine, I think?

**Comment by lunelson** [comment]
I think I need a way to just reinstall ruby completely on this machine. I now can't even get past `bundle install`, I get

```sh
Could not load OpenSSL.
You must recompile Ruby with OpenSSL support or change the sources in your Gemfile from 'https'
to 'http'. Instructions for compiling with OpenSSL using RVM are available at
rvm.io/packages/openssl.
```
Any tips?

**Comment by nex3** [comment]
I think you will need to reinstall Ruby. Installing via RVM is pretty easy, though.

**Comment by lunelson** [comment]
@nex3 OK got it, thanks. For some reason, RVM was complicated on macos High Sierra but `rbenv` installed via Homebrew worked the first time. The original error here continued; but deleting the `spec.files` line as you suggested worked 😅

**Comment by nex3** [comment]
Sorry it's been so much trouble!

**Comment by stof** [comment]
@nex3 I suggest closing this as the readme now suggests using the typescript runner.
