### ISSUE TITLE
Unification of :nth-child selectors

### ISSUE THREAD

**Issue by clarcharr** [sass/sass-spec#1212]
SASS currently doesn't combine selectors like `:first-child` and others during unification as it should.

A few examples:

* `selector-unify(':first-child', ':last-child')` => `:only-child`
* `selector-unify(':first-child', ':nth-child(odd)')` => `:first-child`
* `selector-unify(':first-child', ':nth-child(even)')` => (nothing)
* `selector-unify(':nth-child(2n)', ':nth-child(3n)')` => `:nth-child(6n)`

**Comment by nschonni** [comment]
@clarcharr feature requests to the Sass language should go to https://github.com/sass/sass
This repo just represents the tests used by the implementations to confirm compliance

**Comment by clarcharr** [comment]
Will move these issues to that repo.

**Comment by nschonni** [comment]
Thanks :+1:
