### ISSUE TITLE
Option to set seed or run in order?

### ISSUE THREAD

**Issue by tmastny** [sass/sass-spec#1276]
Hello, I'm using `sass-spec` to test a new wrapper for `libsass` written in [R](https://github.com/tmastny/sass). 

I've been able to [run](https://github.com/tmastny/sassr-test) the `sass-spec` tests against my implementing using 
```
sass-spec/sass-spec.rb -c ./sassr.R
```
but the random seed has been making it difficult to compare tests across runs. Is there a way to set the seed? I don't see any setting with 
```
./sass-spec.rb -h
```
and I couldn't finding any mention of `--seed` in the source code either. 

Is there anyway to set the seed? If not, is this a feature you would consider?

Thanks

**Comment by nex3** [comment]
As far as I know, none of the specs actually produce nondeterministic output whether or not a seed is set. Are you seeing a spec whose output changes from run to run?

**Comment by tmastny** [comment]
The spec results are the same, but I'm piping the results to a file (say `results.txt`). It would be nice to if the `results.txt` files were the same between runs. 

That way if I make a change to the wrapper, I can compare the results side by side. Likewise if I compare the R wrapper to say `node-sass` or `sassc`. 

For example, on my machine and installation running `node-sass` against the specs gives 
> 2034 runs, 1555 assertions, 479 failures, 0 errors, 0 skips

where the R wrapper gives

> 2034 runs, 1740 assertions, 294 failures, 0 errors, 0 skips

I'd love to be able to do a side-by-side comparison of the results, or better yet do a diff to see which tests fail on R but pass on node.

**Comment by nex3** [comment]
I believe the order the specs are run is determined by the Ruby test runner that's being used, but I don't know the details about that. Maybe @nschonni knows more?

**Comment by nschonni** [comment]
node-sass wrapper is here https://github.com/sass/node-sass/blob/master/test/spec.js since it doesn't depend on the Ruby runner. It also uses a tagged copy of this repo published to NPM, so that might be part of the reason you're seeing different numbers

**Comment by nex3** [comment]
@nschonni Do you know if there's a way to get the Ruby runner to run specs in a consistent order?

**Comment by nschonni** [comment]
Don't think minitest supports it from a 30 second search https://stackoverflow.com/questions/29991869/how-do-you-specify-the-exact-order-of-minitest-tests#29994690
If you're A/B testing files, i'd just sort the files before comparison

**Comment by stof** [comment]
@nex3 this is solved by the new typescript runner, right ?

**Comment by nex3** [comment]
Yes, the typescript runner runs tests in a deterministic order.
