### ISSUE TITLE
Unescaped control char expected in spec/values/identifiers/escape/normalize ?

### ISSUE THREAD

**Issue by kaj** [sass/sass-spec#1287]
In the test spec/values/identifiers/escape/normalize, in the line `non-printable:` a bunch of controll characters from `\0` to `\1E` is given as hex escapes and expected to show up as hex escapes in the output.  But then `\1F` is given, and expected to show up as a backslash followed by the actual U+001F character (unit separator).  This character is listed as not printable in my unicode reference, so as far as I can see it should probably appear escaped as `\1f` in the output?

I checked the commit history of the test, but found no clue, other than that it is fairly recent (created in 8b43346bfe4, and updated once in df44d3aaa)

**Comment by nex3** [comment]
Good catch! This is a bug in the spec.
