### ISSUE TITLE
Stop using language versions for LibSass

### ISSUE THREAD

**Issue by nex3** [sass/sass-spec#1297]
Currently, LibSass runs specs on Travis against version 3.5 and 3.6 of the language. With the deprecation of Ruby Sass, we're also deprecating the idea of versions of the Sass language. Implementations now just support certain sets of features instead, which we're representing in sass-spec as specs that are or are not marked as TODO. LibSass specs should move to this model; in other words, they should be able to run in 4.0 mode and just have any features that aren't implemented yet skipped as TODO.

**Comment by xzyfer** [comment]
LibSass specs have been updated in #1309

**Comment by nex3** [comment]
@xzyfer is there a reason this is still open, or can I close it out?

**Comment by xzyfer** [comment]
I left it open because ruby sass was still using language versions. Wasn't
sure if that was going to be removed also.

**Comment by nex3** [comment]
Removing versions entirely is tracked by #1223; this issue is just for LibSass to stop using them.
