### ISSUE TITLE
Whitespace isn't always treated as significant

### ISSUE THREAD

**Issue by xzyfer** [sass/sass-spec#131]
We're getting to the point now where spec are being written for stylistic issues. e.g.

https://github.com/sass/sass-spec/pull/127
https://github.com/sass/sass-spec/pull/114
https://github.com/sass/sass-spec/pull/113
https://github.com/sass/sass-spec/pull/112

It appears that some cases the test-runner doesn't see whitespace as significant, which it is in stylistic terms.

An example of this broken behaviour is https://github.com/sass/sass-spec/pull/127/files. This spec although clearly broken (http://sassmeister.com/gist/9b125ed4200df25a4dd6) passes.

**Comment by chriseppstein** [comment]
if we were to have a `details.json` file per test we could flag some tests as whitespace sensitive.

**Comment by xzyfer** [comment]
I believe the spec runner used to have this capability at some point. I've
seen .cfg files set alternate output styles to test compressed output style
features.

**Comment by mgreter** [comment]
I have started working on making libsass better white-space aware:
https://github.com/sass/libsass/pull/839

Not sure if this will be ready in 3.2. It should also make it pretty easy to implement to other output styles with the refactoring in place!

**Comment by mgreter** [comment]
We now test whitespace much more accurate!
We currently only normalize multiple linefeeds!
