### ISSUE TITLE
--probe-todo no longer outputs the list of newly passing tests

### ISSUE THREAD

**Issue by glebm** [sass/sass-spec#1321]
I use the following command (via a Makefile) when working on libsass:

```bash
$(RUBY_BIN) $(SASS_SPEC_PATH)/sass-spec.rb -V 3.5 -c $(SASSC_BIN) --impl libsass --probe-todo $(LOG_FLAGS) $(SASS_SPEC_PATH)/$(SASS_SPEC_SPEC_DIR)
```

It is very useful to quickly see if my refactorings / cleanups fix any known bugs (as they often do).

Recently, this command stopped listing the newly passing specs (took me a while to figure out what's going on).

Does the command need to be adjusted somehow?

**Comment by nex3** [comment]
This is an unfortunate but intended consequence of #1308. `Minitest` doesn't support accessing information about which tests succeeded or failed after the tests are done running, and it had been relying on a big ol' hack to collate this information. My refactor, unfortunately, broke this hack.

However, you should still be able to run with `--probe-todo --interactive` and get interactive notifications about specs that have started passing, with the added bonus that it can automatically remove TODOs as well.

**Comment by nex3** [comment]
Would it work if we had `--probe-todo` cause tests to fail if they pass unexpectedly, even outside of interactive mode?

**Comment by glebm** [comment]
That would make our CI red so it wouldn't work for CI.
If activated by a flag, it'd at least work for local development.

>  it had been relying on a big ol' hack to collate this information

Perhaps just this one hack can be brought back? :pray:

**Comment by nex3** [comment]
Can you help walk me through your use-cases? I'm not sure I totally understand them, and I'd *really* like to find a way to address them that doesn't add hacks. The sass-spec codebase is already gnarly and untested, so anything we can do to keep it cleaner is a big benefit to ongoing maintainability.

**Comment by glebm** [comment]
1) Development:

   I make a change in libsass and I want to see how it affected the tests.
   Previously I'd just run `make test_probe` to get the list of failing and newly passing tests (3 keystrokes).

2) Reviewing PRs:

   A PR comes in. I go to CI and see the list of failing and newly passing tests.
   This is useful if a PR is in progress, or when the contributor did not run `test_probe` themselves (and also didn't send a PR to sass-spec).

   Note that having newly passing tests in this case is not an error.

3) Investigating historical status:

   For example, if I want to find out when a test started passing, often clicking a few Travis links is *much* faster than setting up a git bisect.

/cc @xzyfer @mgreter

**Comment by xzyfer** [comment]
This has also been my workflow for the last couple years. Losing probe-todo
is quite jarring to day to day development.

**Comment by nex3** [comment]
I still don't really understand why having unexpectedly passing tests produce errors isn't a good solution here, but I guess the consensus is clear, so I'll re-add the hack.

**Comment by glebm** [comment]
> I still don't really understand why having unexpectedly passing tests produce errors isn't a good solution here

There is often a delay between changes in libsass and updates to spec-sass, so the build would be red half the time if they produced errors.

Perhaps we could have an `--only-todo` flag (and then we can `run with --only-todo || echo ignore failures` on CI).

**Comment by nex3** [comment]
> There is often a delay between changes in libsass and updates to spec-sass, so the libsass Travis build would be red half the time.

Isn't it a bad thing that there's a delay between changes to libsass and updates to sass-spec? It seems to me that having passing TODOs be a build failure would encourage more up-to-date spec metadata rather than more red builds.
