### ISSUE TITLE
Interactive mode shouldn't delete issue references

### ISSUE THREAD

**Issue by nex3** [sass/sass-spec#1364]
It's good practice to add a reference to a GitHub issue for every implementation marked as `:todo`, both to ensure that the implementation authors know about the `:todo` test and to make it easy to tell if the `:todo` should be removed. However, when `--interactive` mode updates an `options.yml` file, it re-serializes it from a map from scratch which removes any existing comments.

One potential way to fix this would be to build in support for just writing issue references *as* `:todo`s, as in:

```yaml
---
:todo:
- sass/libsass#2840
```

**Comment by stof** [comment]
@nex3 should this be closed as the interactive mode has been rewritten from scratch in typescript in the meantime ?
