### ISSUE TITLE
Add spot-check tests for folders without specs

### ISSUE THREAD

**Issue by nex3** [sass/sass-spec#1433]
Occasionally, directories get left without full specs either because a spec wasn't fully deleted or because of typos like the one fixed in https://github.com/sass/sass-spec/pull/1431. We should have a sanity check that verifies that every directory under `spec/` contains either a spec or subdirectories.

**Comment by stof** [comment]
To avoid breaking specs like https://github.com/sass/sass-spec/pull/1589 which rely on subdirectories by themselves for imports, a third case should be allowed: folders being subdirectories of a folder containing a spec.
