### ISSUE TITLE
Allow running specs against a Dart Sass binary

### ISSUE THREAD

**Issue by jathak** [sass/sass-spec#1540]
Running specs with `--dart` runs Dart Sass from source through a Dart script that runs all specs in a single VM, avoiding the VM startup time for subsequent specs.

However, with `dart2native`, it's now possible to create a Dart Sass executable with minimal startup time. When running small sets of specs repeatedly while refactoring, the single VM startup time exceeds the cumulative startup time of running the native executable for each test.

It would be nice to be able to do `--impl dart-sass -c /path/to/native/dart/sass`, similar to how running libsass tests work, but Dart Sass's CLI is currently not compatible with what sass-spec expects.

Once support for running Dart Sass in this way is implemented, it would also be useful to run benchmarks to see if running a native executable repeatedly is faster than running all specs from source in a single VM.

**Comment by stof** [comment]
I tried looking at the incompatibilities. Here are my findings:

- the spec runner expects to use `$EXECUTABLE -v` to get the version. But dart-sass does not have a shorthand. It only supports `--version`. This can be easy to fix, in 2 different ways:
     - the runner could use `--version` instead, which is supported by dart-sass, sassc and even ruby-sass (for what it brings)
     - dart-sass could add support for the `-v` shorthand, which does not conflict with other options, and could make sense
- the spec runner uses `$EXECUTABLE -t expanded` to set the output style. but `dart-sass` uses a `-s` shortcut here (indeed more logical as a shortcut for `--style`) while `-s` is the shortcut for `--stdin` in sassc and ruby-sass.
    - the runner could be updated to use the `--style` option rather than the shorthand. This name is common to all the CLIs
    - `dart-sass` may add a second `-t` shortcut for `--style` for compatibility with the runner, if this is possible (I have no idea whether an option can have multiple shortcut with the dart args package)

I would say that using `--style` in the runner makes sense to unlock that.
