### ISSUE TITLE
`libsass-closed-issues/issue_2779.hrx` is missing `output.css`

### ISSUE THREAD

**Issue by connorskees** [sass/sass-spec#1550]
In a default run of the sass-spec, `SassSpec::Test#test__sass-spec/spec/libsass-closed-issues/issue_2779` will fail with the error message
```
Expected output.css file does not exist
```
[This test seems to have a file `status` rather than `output.css`](https://github.com/sass/sass-spec/blob/master/spec/libsass-closed-issues/issue_2779.hrx)

Is this behavior intentional? If so, is there a way in which implementations may pass this test when running without any implementation set?

**Comment by stof** [comment]
And the status file is a legacy. see https://github.com/sass/sass-spec/pull/1316
