### ISSUE TITLE
Multi-line support in the indented SASS syntax

### ISSUE THREAD

**Issue by some1else** [sass/sass-spec#1557]
It feels like there should be a solution to manually wrap long lines in the indented sytax.

Example:

```
body
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', 'Roboto', \
    'Oxygen', 'Ubuntu', 'Cantarell', 'Fira Sans', 'Droid Sans', \
    'Helvetica Neue', sans-serif
```
 
There's a [Webpack loader](https://github.com/wrwrwr/webpack-multiline-sass) that successfully implements this approach.

How to go about adding this proposal to the spec? I'm willing to make the PR, but haven't found any [guidelines for contributing](https://github.com/sass/sass-spec/contribute).

Thanks

**Comment by jathak** [comment]
This repo is for the language test suite, not the language specification (the name is a bit confusing).

Language proposals go in the [sass/sass](https://github.com/sass/sass) repo. You can find the guidelines for new proposals [here](https://github.com/sass/sass/blob/master/CONTRIBUTING.md).
