### ISSUE TITLE
Specs for the use directive contain a suspicious spec

### ISSUE THREAD

**Issue by stof** [sass/sass-spec#1602]
`directives/use/error/syntax/member/single_dot` looks suspicious to me. This spec is in the `directives/use` folder, but does not rely on `@use` at all: https://github.com/sass/sass-spec/blob/6015399e4b4ef8de2351e88d8acac3935b9ac00b/spec/directives/use/error/syntax.hrx#L78-L91

So either this spec is not covering the intended behavior, or it is in the wrong location

**Comment by jathak** [comment]
Good catch. It looks like this is with the `@use` specs because it's trying to test an edge case of namespaces, but it makes sense to move this elsewhere
