### ISSUE TITLE
Add a test for libsass regression

### ISSUE THREAD

**Issue by DanielHeath** [sass/sass-spec#1613]
The following sass:
```
form.create /* div */.buttons {
  float: right;
}
```
should generate the selector `form.create .buttons`.

Sometime between libsass 3.5.5 and 3.6.1 it started generating `form.create.buttons` instead (dropping the space).

This case is therefore probably not tested. Worth adding?

**Comment by stof** [comment]
I would say yes (but following the guidelines, so using single char placeholders)

**Comment by nex3** [comment]
Closed due to lack of response.
