### ISSUE TITLE
TS runner interactive mode chokes on malformed test cases

### ISSUE THREAD

**Issue by nex3** [sass/sass-spec#1648]
If a test case is missing the `output.css` file (perhaps because it's incorrectly named `output.scss`), the TypeScript runner's interactive mode will get into a bad state where it will report errors for all tests run after the broken test, but won't print actual diagnostic information for any of them.

**Comment by stof** [comment]
@nex3 is this fixed by https://github.com/sass/sass-spec/pull/1687 ?

**Comment by nex3** [comment]
Yes, thanks!
