### ISSUE TITLE
Ability to ignore error messages/spans and deprecation warnings

### ISSUE THREAD

**Issue by connorskees** [sass/sass-spec#1679]
Error messages/spans and deprecation warnings create a lot of noise when testing against the spec, but aren't necessarily useful to test against. Especially warnings like `DEPRECATION WARNING: Using / for division is deprecated and will be removed in Dart Sass 2.0.0.`, which is the cause for 50+ errors, but can never reasonably be fixed since the message contains the string "Dart Sass"

**Comment by nex3** [comment]
This is why we have the ability to define different outputs for different implementations. Maybe it's time to add Rust Sass to this repo as an officially-tested implementation?

**Comment by nex3** [comment]
Closing this out for now, let me know if you want to start the process of adding Rust Sass to this repo.

**Comment by connorskees** [comment]
Would having to support a Rust implementation of Sass increase the maintenance burden on this repository?

In my local development, I maintain a forked version of this repository with `trimErrors` and `skipWarnings` set to always be `true`. I think the ability to pass a flag that would set these two values would be sufficient for my use case. 

https://github.com/sass/sass-spec/blob/a5d4b0ce5f8f03312f2f67cc36960ecc94069110/lib/test-case/test-case.ts#L124-L126

I can upstream my changes at some point in the near future if this change makes sense.

**Comment by nex3** [comment]
Tracking Rust Sass would be a bit more effort, but it's not onerous. sass-spec is designed to track multiple implementations.

If you'd prefer not to, I'd also accept a PR to add `--ignore-error-diffs` and `--ignore-warning-diffs` flags to the CLI.

**Comment by nex3** [comment]
@connorskees What are your thoughts here?
