### ISSUE TITLE
[Proposal] Disable the embedded-host JS API tests until the setup is fixed

### ISSUE THREAD

**Issue by stof** [sass/sass-spec#1724]
Currently, the installation steps of the embedded-host JS API tests are failing, making the CI red for all PRs. This blocks all changes on the language specs, which are independent from the JS API tests.
I suggest marking the embedded-host jobs as skipped until someone has time to fix the setup, to unblock the situation.

**Comment by Awjin** [comment]
This is being addressed here https://github.com/sass/embedded-host-node/pull/65

**Comment by nex3** [comment]
The fix is in, so I think we can close this out.

**Comment by stof** [comment]
Indeed, the CI is green again. And I rebased/amended all my opened PRs to re-trigger the CI on them, to make them mergeable.
