### ISSUE TITLE
spec linter should allow large HRX files if they are test units

### ISSUE THREAD

**Issue by Goodwine** [sass/sass-spec#1821]
Related: https://github.com/sass/sass-spec/pull/1817

Currently the linter (and fixer) will break up any HRX file longer than 500 lines
This may be too extreme for the sake of unit-testing because it separates inputs and outputs

By doing this we can also merge the directory traversal logic since we'll stop at "test dirs"

**Comment by stof** [comment]
When doing that, it should merge back test dirs that wre broken down by #1817

**Comment by Goodwine** [comment]
yup, that;s part of the plan :)
