### ISSUE TITLE
The specs for meta.feature-exists don't actually enforce an interoperable behavior

### ISSUE THREAD

**Issue by stof** [sass/sass-spec#1939]
Currently, the specs for `feature-exists` are expected all known features to return `true`.

This does not ensure that an implementation returns a value that is actually consistent with whether it implements the feature. And I'm not even sure we have an exact definition of what would be required for each feature to return true.

It might be great to find a way to write those specs if a way that actually tests that the implementation behaves accordingly to its reported status.

**Comment by stof** [comment]
Alternatively, maybe this function should be deprecated. The known features are only old ones.

**Comment by nex3** [comment]
I think the function should probably be deprecated. In practice, almost all the new features we add fall into one of three categories:

1. New built-in functions or mixins, which are easy to detect using other `sass:meta` functions.
2. Language-level features which are relatively easy to detect on their own (for example, first-class calc can be detected with `calc(1 + 1) == 2`).
3. New syntax which can't even be parsed in implementations that don't support it, for which feature detection isn't particularly useful anyway.
