### ISSUE TITLE
Support the indented syntax

### ISSUE THREAD

**Issue by xzyfer** [sass/sass-spec#247]
Looks like Libsass has issues with indented syntax that aren't in the scss syntax https://github.com/sass/libsass/issues/845. As is stands we follow the normal procedure of writing a spec because sass-spec.rb can only handle one format per run.

This is likely related to https://github.com/sass/sass-spec/issues/82, and https://github.com/sass/sass-spec/issues/46.

/cc @chriseppstein

**Comment by saper** [comment]
Closed via #503.
