### ISSUE TITLE
selector functions type checks / error checks

### ISSUE THREAD

**Issue by onedayitwillmake** [sass/sass-spec#302]
While implementing the 3.4 selector functions, I know how sensitive they can be to bad input. 
Currently our test (https://github.com/sass/sass-spec/tree/master/spec/libsass-todo-issues/issue_963/selector-functions), are only being passed ideal input values.

Can we add checks to make sure the passed in types are correct (for example passing in "12" in some functions is considered bad.

The ruby sass test suite has some methods for that, but i'm not sure what the format would be to translate those here.

For example:
```
    assert_error_message("$selectors: At least one selector must be passed for `selector-append'",
      "selector-append()")
    assert_error_message("Can't append \"> .bar\" to \".foo\" for `selector-append'",
      "selector-append('.foo', '> .bar')")
    assert_error_message("Can't append \"*.bar\" to \".foo\" for `selector-append'",
      "selector-append('.foo', '*.bar')")
    assert_error_message("Can't append \"ns|suffix\" to \".foo\" for `selector-append'",
      "selector-append('.foo', 'ns|suffix')")
```

**Comment by onedayitwillmake** [comment]
+ @xzyfer

**Comment by xzyfer** [comment]
@onedayitwillmake good call however unfortunately sass-spec currently cannot assert errors https://github.com/sass/sass-spec/issues/136

**Comment by xzyfer** [comment]
For the moment you can open a PR with the error message in the output file i.e. https://github.com/sass/sass-spec/pull/290/files

**Comment by saper** [comment]
@xzyfer matching against the output file is unlikely to work. When running with `sassc` you'll get it on stderr and for Ruby it depends on the spec invocation style (CSS-formated exception on stdout when not using `-c` or stderr when using the Sass CLI process).

**Comment by saper** [comment]
@onedayitwillmake I have prepared the solution in #494 (for error testing) feel free to try testing with this PR applied. It should be possible to check for error messages!
