### ISSUE TITLE
Warning: `compact` has been removed breaks node-sass coverage

### ISSUE THREAD

**Issue by saper** [sass/sass-spec#360]
My environment:

- sass/node-sass@2fce3035ba2374517d42ae4654bd354fa417d20d (master as of now)
- libsass 3.2.1 (sass/libsass@e716caa918d86b3b8598e8ad639943fe6ec8e0e) (master as of now)
- sass/sass-spec@3dafe99cff8de105116ee4c08cfda162d2e3a0d (master as of now)

(libsass has been compiled separately and linked to the node-sass binding as a shared library)

When running `npm test` I get the following warning:

````
      ✓ bool
Warning: `compact` has been removed from libsass because it's not part of the Sass spec
Warning: `compact` has been removed from libsass because it's not part of the Sass spec
Warning: `compact` has been removed from libsass because it's not part of the Sass spec
Warning: `compact` has been removed from libsass because it's not part of the Sass spec
      ✓ bourbon (43ms)
      ✓ calc
````

but the tests pass. Trying however to run `mocha` in the coverage testing mode fails immediately:

````
>  npm run coverage

> node-sass@3.0.0-beta.7 coverage /home/saper/node_modules/node-sass
> node scripts/coverage.js

Warning: `compact` has been removed from libsass because it's not part of the Sass spec


npm ERR! FreeBSD 10.1-STABLE
npm ERR! argv "node" "/usr/local/bin/npm" "run" "coverage"
npm ERR! node v0.12.2
npm ERR! npm  v2.8.4
npm ERR! code ELIFECYCLE
npm ERR! node-sass@3.0.0-beta.7 coverage: `node scripts/coverage.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-sass@3.0.0-beta.7 coverage script 'node scripts/coverage.js'.
npm ERR! This is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/coverage.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/saper/node_modules/node-sass/npm-debug.log
````

Maybe the warning should be relaxed or compact test files removed from the spec?

Ping sass/node-sass#904 sass/libsass#1055 sass/sass-spec#359

**Comment by xzyfer** [comment]
@mgreter  this is what I was worried about. Users are now getting warned even if they've defined their own `compact` function. I'm just going to remove `compact` for good.

**Comment by saper** [comment]
Isn't that because test contain `...compact.css` files?

**Comment by xzyfer** [comment]
No. We originally had a native `compact` function in Libsass. It was removed in 3.2.0 because it was non-standard. In 3.2.1 we started throwing a warning you tried to used the `compact` function, however the code doesn't only warning if you're trying to use the native version i.e. if you have defined your own `compact` function.

**Comment by saper** [comment]
Why `bool` test generates a warning?

**Comment by xzyfer** [comment]
I believe the error is from the bourbon spec below, which defines it's own compact function.

**Comment by xzyfer** [comment]
Please try with this patch. https://github.com/sass/libsass/pull/1156

**Comment by mgreter** [comment]
@xzyfer Go for it, but I wonder why this did not happen with official spec tests. I mean bourbon is part of the official spec test suite!? But appologies if the warning causes any problems!??

**Comment by xzyfer** [comment]
@mgreter Yeah couldn't reproduce it either.

@sapar I've released libsass 3.2.2 - https://github.com/sass/libsass/releases/tag/3.2.2

**Comment by xzyfer** [comment]
We knew this was going to happen, didn't expect it to affect node-sass though

https://github.com/sass/libsass/pull/1055#discussion_r28054592

**Comment by saper** [comment]
@xzyfer I have more fixes for sassc so pls hold your horses :)

**Comment by xzyfer** [comment]
I haven't yet released sassc.

**Comment by saper** [comment]
Thanks, it works now!
