### ISSUE TITLE
Broken Builds ;(

### ISSUE THREAD

**Issue by hcatlin** [sass/sass-spec#361]
Apparently we have a lot of broken and builds against Sass 3.4.13

https://travis-ci.org/sass/sass-spec/builds/60883789

Can I nuke and fix these?

@mgreter it seems like your test of using non-utf-8 characters broke Ruby Sass... spec/libsass/length

**Comment by mgreter** [comment]
Are you telling ruby sass to use utf8 encoding? IMHO I had to use `sass -E UTF-8` to have it behave correctly, but thought that was a windows only issue ...

**Comment by xzyfer** [comment]
I've looked into this further. Aside the form UTF-8 spec mentioned above, there are two failing test.

**spec/libsass/scale**

Looks to be a rounding error with colours.

```
-  color: #c85ae6;
+  color: #c85ae5;
```

**spec/libsass-closed-issues/issue_614**

Regarding `@support` output. This has been acknowledged as a bug in Sass https://github.com/sass/sass/issues/1512#issuecomment-95376786.

**Comment by mgreter** [comment]
For the rounding error see https://github.com/sass/sass/issues/1690

**Comment by xzyfer** [comment]
Using `-E` doesn't fix this on OSX

```
$ sass -E UTF-8 spec/libsass/length/input.scss
Error: Invalid UTF-8 character "\xE9"
        on line 7 of spec/libsass/length/input.scss
  Use --trace for backtrace.
```

**Comment by mgreter** [comment]
Can you confirm it works on windows?
Otherwise I could give it another try in a few hours ...

**Comment by xzyfer** [comment]
I think this might be related to some Windows UTF-8 issue. Once I open and saved the file OSX it worked file.

Here's the diff https://github.com/sass/sass-spec/pull/377

**Comment by xzyfer** [comment]
I can't test on Windows atm.

**Comment by mgreter** [comment]
A hex diff would help me most (too see which encoding we actually had) ...

**Comment by xzyfer** [comment]
https://www.diffchecker.com/h6nzbjaq

**Comment by mgreter** [comment]
OK, so the left text is "old-school" ascii "latin-1" encoded. Libsass tries to parse it as utf8, which uses the upper half of the ASCII table for it's encoding (leaving the lower half as is). We could come up with something that first checks if the file not only "looks" like utf8, but is also valid utf8 and fallback to "latin1" ascii table. At least it is clear now what was causing this issue.

**Comment by xzyfer** [comment]
Come up with something where? Libsass passes this spec. Ruby Sass crashed.
I don't know there's anything we need to do here other than fix the spec to
be valid utf-8 and call it day.

**Comment by mgreter** [comment]
Ah, I see, my bad. Just thought we could fallback to ISO if we detect invalid utf8 (bascially just interpret it byte by byte then). But that wouldn't really make much sense either IMO.

**Comment by xzyfer** [comment]
I'll ship #377 which will fix this test. AFAIK this is also the only thing that stop us get 100% on https://sass-compatibility.github.io/#string_manipulation_functions

**Comment by xzyfer** [comment]
With Sass 3.4.14 we're now passing in CI. Closing.
