### ISSUE TITLE
Error output: SassEngineAdapter cannot be reliably parallelized

### ISSUE THREAD

**Issue by saper** [sass/sass-spec#499]
SassEngineAdapter attempts to redirect standard error output coming from the Sass module:
```
    begin
      captured_stderr = StringIO.new
      real_stderr, $stderr = $stderr, captured_stderr
      begin
        css_output = Sass.compile_file(sass_filename.to_s, :style => style.to_sym)
        [css_output, captured_stderr.string, 0]
      rescue Sass::SyntaxError => e
        ["", "Error: " + e.message.to_s, 1]
      rescue => e
        ["", e.to_s, 2]
      end
    ensure
      $stderr = real_stderr
````

This unfortunately does not work reliably, since we ask MiniTest to parallelize testing and $stderr redirection is global.

When running some test very fast one notices that sometimes stderr output is not captured, sometime one test captures stderr of two tests etc. This is because at the time we try to redirect
the stderr is already redirect in some other test.

The solution is to:
- abandon SassEngineAdapter (which was introduced in ba737f54f4ad5083ea33f0322bb5104309010717 for speed)
- abandon parallel tests
- find better way to capture errors from Sass.

**Comment by chriseppstein** [comment]
This is a bug in Ruby sass that I will fix.

**Comment by chriseppstein** [comment]
According to http://chriskottom.com/blog/2014/10/exploring-minitest-concurrency/ using standard (mri) ruby, enabling concurrency will make our tests as much as 25% slower because of the global interpreter lock (GIL).

I'm not sure this is worth addressing.
