### ISSUE TITLE
Report disabled tests

### ISSUE THREAD

**Issue by saper** [sass/sass-spec#506]
Directories which do not have valid input files (or output files before #494) are silently skipped. 
This is how not-really-magic `disabled` keyword works (renaming `input.scss` to `input.disabled.scss`).

````
> ruby sass-spec.rb -c ~/sw/sass/bin/sass -s spec/libsass-todo-tests/css_error_with_windows_newlines
Recursively searching under directory 'spec/libsass-todo-tests/css_error_with_windows_newlines' for test files to test '/home/saper/sw/sass/bin/sass' with.
Sass 3.4.14.2e0f33b (Selective Steve)
Run options: --seed 19577

# Running:



Finished in 0.001196s, 0.0000 runs/s, 0.0000 assertions/s.

0 runs, 0 assertions, 0 failures, 0 errors, 0 skips
````

This is confusing especially given there is always a chance for a typo. See also #501 and #505 for funny cases where it confuses people.

I think we should add those directories to "skips" to indicate this. Especially useful when running against a single or a small group of directories.

**Comment by saper** [comment]
Of course, directories containing only some other directories (sub-tests) should not be reported.

**Comment by chriseppstein** [comment]
There's no disabled concept any more. tests can be marked as todo.
