### ISSUE TITLE
Nuke is not idempotent

### ISSUE THREAD

**Issue by xzyfer** [sass/sass-spec#533]
Discovered in https://github.com/sass/sass-spec/pull/529.

If a spec is nuke'd multiple times, and one run produces an error, the error file is never cleaned up.
I expect the same applies in the inverse. If nuking an error spec multiple times and one mistaken produces output, this output is not cleaned up (untested).

**Comment by saper** [comment]
Yes, I know that and this will be fixed soon. I have the same problem with `--generate`.

**Comment by chriseppstein** [comment]
I fixed this as I was working on things. See: https://github.com/sass/sass-spec/blob/master/lib/sass_spec/test.rb#L398-L400.

Also, nuke is gone, use `-g` now.
