### ISSUE TITLE
Errors may not be equal for all output styles

### ISSUE THREAD

**Issue by mgreter** [sass/sass-spec#627]
As I suspected, there are some errors which differ for varying output styles. Today the check I've added in the perl-libsass runner (I mentioned that in a slack chat AFAIR) catched a first sample:

```scss
foo {
  bar: (rgba(16,16,16,0.5) + #AAA);
}
```

results
```
Error: Alpha channels must be equal: rgba(16,16,16,0.5) + #AAA // compressed
Error: Alpha channels must be equal: rgba(16, 16, 16, 0.5) + #AAA // all others
```

//CC @saper

**Comment by mgreter** [comment]
@chriseppstein should errors, warnings and inspect at all respect the output styles and precision settings? This seems not 100% consistent with ruby sass all the times (so far I thought it is ignored).

**Comment by saper** [comment]
@mgreter can you just prepare one directory with 4 subdirectories, 4 identical input.scss files in every one of them, and only one expected*css file per directory? You can use `sass-spec -g format` to generate them one by one.

**Comment by mgreter** [comment]
Not sure if I understand correctly, but how does the spec runner know which output style it has to produce? Or do you just want the files, because I already pushed them to a [local branch] [1].  I actually would propose a structure like this, since I already support this in perl-libsass :)
![sass-error-specs](https://cloud.githubusercontent.com/assets/282293/11411526/f7999d4e-93d0-11e5-8541-e4c58036bfd3.png)
If the optional files don't exists, I expect the default exit code and nothing on stderr ...

[1]: https://github.com/mgreter/sass-spec/tree/test/value-op-errors/spec/errors/subtract/alpha-channels-todo

**Comment by xzyfer** [comment]
Personally I would like to see this addressed upstream. I've opened an issue to discuss this https://github.com/sass/sass/issues/1916

**Comment by mgreter** [comment]
IMHO we would still need different tests if the error reporting is according to output style settings (and ie. precision). Currently we take it for "granted" that errors will be reported the same for all settings. If that would change, we still would need support to test stderr for different options. So IMHO my proposal is still valid, and I'd rather test too much then too little.

**Comment by saper** [comment]
This is my proposed solution to the problem: https://github.com/sass/sass-spec/pull/629

quite simple imho and no changes to sass-spec needed

after putting `input.scss` in the respective directories I did:

````
ruby -I /home/saper/sw/sass/lib /home/saper/sw/libsass/sass-spec/sass-spec.rb -c /home/saper/sw/sass/bin/sass  -g nested -g expanded -g compact spec/errors/addition/alpha-channels-todo/normal
ruby -I /home/saper/sw/sass/lib /home/saper/sw/libsass/sass-spec/sass-spec.rb -c /home/saper/sw/sass/bin/sass  -g compressed spec/errors/addition/alpha-channels-todo/compressed

ruby -I /home/saper/sw/sass/lib /home/saper/sw/libsass/sass-spec/sass-spec.rb -c /home/saper/sw/sass/bin/sass -g nested -g expanded -g compact  spec/errors/subtraction/alpha-channels-todo/compressed
ruby -I /home/saper/sw/sass/lib /home/saper/sw/libsass/sass-spec/sass-spec.rb -c /home/saper/sw/sass/bin/sass  -g compressed spec/errors/subtraction/alpha-channels-todo/compressed
````

**Comment by saper** [comment]
When testing for errors only I usually use only one output format, but in this cases we can make an exception.

**Comment by saper** [comment]
An alternative and much simpler solution is in #631. We simply do not need to test for 4 output formats if the only result is an error message (generated output files are empty).

The approach in #631 has also an advantage in a situation where Ruby Sass compressed output format changes we don't need to change that test.

This test case was generated simply with

````
ruby -I /home/saper/sw/sass/lib /home/saper/sw/libsass/sass-spec/sass-spec.rb -c /home/saper/sw/sass/bin/sass  -g nested spec/errors
````

**Comment by xzyfer** [comment]
I agree with @saper and @chriseppstein. I see no value in testing error messages in for alternate output modes.

We may still eventually have to address testing deprecation warning however. Since in this case the test will generate output and a deprecation message which (i believe?) we pipe into the error file.

**Comment by mgreter** [comment]
@xzyfer was there any statement yet, that errors should always be the same for all possible options? IMHO this will only work if we have this guarantee from upstream sass.

**Comment by saper** [comment]
In general it is also important (although maybe not top-priority) to have an error message compatibility as well. I think we should be pragmatic and let's not cast the original implementation behaviour into stone as the "spec", especially in the edge cases. Therefore I'd vote for "ignore for now" option.

**Comment by xzyfer** [comment]
IMO we should only have `expected_output.css` for error specs.

**Comment by chriseppstein** [comment]
My recent changes make it so that each spec has only one expected output (and output format) and therefore warnings on a per-spec basis can be set accordingly.
