### ISSUE TITLE
Specing sass functions

### ISSUE THREAD

**Issue by scottdavis** [sass/sass-spec#64]
Whats the best approach here. This may be kinda an edge case but how do you plan to handle sass functions that may have different output across different sass versions?

Example: http://sass-lang.com/documentation/Sass/Script/Functions.html#feature_exists-instance_method

**Comment by chriseppstein** [comment]
You can now mark a spec as ignored for a particular implementation and so we can handle this by creating multiple versions of the test with different outputs that would be tested only on one impl or another.

You can also ignore just warnings if that's where the main difference lies.
