### ISSUE TITLE
Issues with unicode and spec runner

### ISSUE THREAD

**Issue by mgreter** [sass/sass-spec#714]
Please see https://github.com/sass/sass-spec/pull/713 and https://travis-ci.org/sass/sass-spec/builds/103013873

They should pass, but fail due to different encoding (spec runner seems not to recognise it correctly)

**Comment by am11** [comment]
Shall we try changing https://github.com/sass/sass-spec/blob/ff9608b/lib/sass_spec/test_case.rb#L114 to:

```ruby
@expected_error = _clean_error(File.read(@error_path, :binmode => true, :encoding => "UTF-8"))
# same fix few lines below (under expected_status)
```
