### ISSUE TITLE
expected_output.css is not generated (neither with -g nor --nuke)

### ISSUE THREAD

**Issue by mgreter** [sass/sass-spec#778]
It is only updated once it exists - it should be created if requested

**Comment by chriseppstein** [comment]
I can't reproduce this.

![sass-spec zsh 2016-04-22 13-25-08](https://cloud.githubusercontent.com/assets/1839/14754021/a57f711e-088d-11e6-8d3f-5c821f881a62.png)

**Comment by mgreter** [comment]
Will give it another try later, brace yourself to be flooded by PRs ;)

**Comment by chriseppstein** [comment]
@mgreter uh. yeah, I had been restructuring the directories somewhat, but I will abort that and wait until  you're done.

**Comment by mgreter** [comment]
Well I just create tests in libsass-todo-tests, should not get any merge conflicts ...

**Comment by saper** [comment]
`-g` needs an argument:

````
m> rm -rf spec/basic/foo
m> mkdir spec/basic/foo
m> echo 'div { color: white; } ' > spec/basic/foo/input.scss
m> ruby \
    -I /home/saper/sw/sass/lib \
    /home/saper/sw/libsass/sass-spec/sass-spec.rb \
    -c /home/saper/sw/sass/bin/sass \
    -g nested spec/basic/foo
Recursively searching under directory 'spec/basic/foo' for test files to test '/home/saper/sw/sass/bin/sass' with.
Sass 3.4.14.2e0f33b (Selective Steve)
Run options: --seed 57991

# Running:

.

Finished in 0.411813s, 2.4283 runs/s, 12.1414 assertions/s.

1 runs, 5 assertions, 0 failures, 0 errors, 0 skips
m> find spec/basic/foo
spec/basic/foo
spec/basic/foo/input.scss
spec/basic/foo/expected_output.css
m> cat spec/basic/foo/expected_output.css
div {
  color: white; }
````

**Comment by chriseppstein** [comment]
`-g` doesn't take an argument and is functionally equivalent to `nuke` at this point based on my reading of the code. was it the intent that -g and --nuke behave differently?

**Comment by saper** [comment]
I have introduced it in #509 and it always have had an argument... (unless I have heavily misunderstood something).

My problem with `--nuke` is that it only re-generates existing output formats. It does not know how to create new ones or create the test from scratch (when having only `input.scss` in the directory).

`--generate all` could have superseded `--nuke` but `--nuke` has a useful test case - just regenerate the results for the existing output formats.

I needed `-g` after https://github.com/sass/sass-spec/pull/494 to test for error cases - it makes no sense to test for 4 output formats if the only expected result for all of them is the error message.
Also many test cases don't need all 4 output formats (I know there is a discussion somewhere else to get rid of them completely). For me `-g format` is a gentle way to move into this direction.

**Comment by chriseppstein** [comment]
@saper There's only one output format per test case now, so after my recent work, it seems that the two options have degenerated into being the same.

**Comment by saper** [comment]
Didn't know that. In that case `-g` is now something different :) 

Yes,  the current code has conflated them completely. Previously you couldn't `--nuke` to create new output files from scratch.

So I think it's time to drop one of them I guess!

**Comment by chriseppstein** [comment]
@saper ok. I've dropped `--nuke` in favor of `-g` or `--generate`
