### ISSUE TITLE
[FR] Add automated way to create bug/todo spec tests

### ISSUE THREAD

**Issue by mgreter** [sass/sass-spec#847]
Extracting feature request from https://github.com/sass/sass-spec/issues/845

As a user or dev I would like to easily
1) create and submit new spec tests for bugs
2) activate passing spec tests
3) push these to personal github repo
4) automatically create a pull request

I already took a [first shot] [1] at this with `gen_libsass_todo`. There are quite a few problematic steps involved, mainly due to the interaction with git. The workflow I implemented in that batch file is:

- take issue number from input
- read content for test from `%issue%.scss`
- fetch latest version from upstream git (i.e. origin)
- create branch `todo/issue_%ISSUE%` from master
- create folder in todo-tests and copy test case
- run sass-spec to generate files for expected output
- add files to git and commit with standard message
- optionally push to remote repository (2nd argument)

I think this per se is pretty much the minimal workflow I would expect to support devs (and would fulfill point 1). The process is error prone, as it is vital to how we interact with git. One question is how fault-tolerant it must be. IMO it will never be 100% bullet proof, just too many variables in between local and remote. I see most problems on the local side, since we need to create new branches (I guess that is a given), since that is only possible with a clean tree. There are a lot of abort conditions we need to check and the question remains how far we want to try to help the user to resolve any git problems.

I guess in a first shot we need to rely on the help of potential users (probably just "us") to progress from there. If you mess up you may need to remove remote branches that were created so you can push again and so on. My only hope here is that we probably can use a ruby git binding (I suspect such a thing exists?) to make our live easier with interacting with git (therefore giving end-users a better experience).

Ultimately we may want to directly create github issues through automated bug reports (automatically attaching the offending code, if you want to got that far). But in the end this always has to do with authentification at some point. And for me that's were it definitely becomes infeasible.

Initial request/goal for me would be to get something up and running in official spec-runner similar to [gen_libsass_todo] [2] batch script. For me it has proven to work pretty well, so I personaly am not even really in a hurry to get it baked into official sass-spec runner. But the long term use-case for such a bug reporting system seems appealing, even though I'm not yet sure how this could play out (just think of how firefox etc. include bug reporting tools out of the box nowaday).

[1]: https://github.com/sass/sass-spec/tree/master/tools
[2]: https://github.com/sass/sass-spec/blob/master/tools/gen_libsass_todo.cmd

**Comment by chriseppstein** [comment]
This is very libsass specific, I'm not sure it belongs in sass-spec.

**Comment by chriseppstein** [comment]
I'm going to close this, but feel free to re-open if you disagree.
