### ISSUE TITLE
In --interactive mode, print the name of the test in question

### ISSUE THREAD

**Issue by nex3** [sass/sass-spec#865]
When I run into an error with `--interactive`, it would be nice to see the filename being tested so that I have a sense of the feature whose spec isn't passing.

**Comment by nex3** [comment]
It looks like sometimes it prints "In spec/whatever/whatever", but sometimes it doesn't. I'm not sure what the different is.

**Comment by chriseppstein** [comment]
Good suggestion. Fixed!
