### ISSUE TITLE
Add a flag to merge specs targeting different Sass versions

### ISSUE THREAD

**Issue by nex3** [sass/sass-spec#866]
It's easy to split a spec into a version that targets an older version of Sass and one that targets a newer version, but if this split ends up being incorrect, it's difficult to merge them again. It would be nice to have a way of doing this automatically. Bonus points if `--interactive` mode detects that the actual output of a failing test is the same as the expected output of a different version and presents an option for merging.

**Comment by chriseppstein** [comment]
This one is trickier, but definitely needed. We need a either define a good heuristic for "another version of a test" or else, I need to track this as explicit metadata. I started working on this in 4244d3bdfcf81fcc37504cdb67814fc05d955b8f but currently, it's disabled.

**Comment by stof** [comment]
@nex3 this should be closed as there is no separate specs per version anymore.
