### ISSUE TITLE
Interactive mode: don't continue if a test can't be migrated

### ISSUE THREAD

**Issue by nex3** [sass/sass-spec#873]
Sometimes when I select the "Migrate copy of the test to pass current version" option in interactive mode, I get the error "Cannot migrate test. Test does not apply to an earlier version"—which makes sense. But then the test runner just starts testing new tests. I'd expect it to let me try choose a different option for the test I tried to migrate, such as updating the expected output.

**Comment by stof** [comment]
@nex3 is this still relevant for the new typescript runner ?
