### ISSUE TITLE
[FR] Generate list of tests and status to markdown

### ISSUE THREAD

**Issue by nschonni** [sass/sass-spec#923]
I was thinking something like the following

| Test Name (or Path?) | 3.4 | 3.5 | 4.0 |
| --- | --- | --- | --- |
| Something Todo in 3.5+ | P | T | T |
| Something 4 specific | - | - | P |
| Something Failing in 3.5 | P | F | P |

Not sure if it makes sense on a "per suite"/folder, and also include a visualization of some of the options

**Comment by xzyfer** [comment]
Is this similar to?

```
./sass-spec.rb annotate --report spec/basic
```

Maybe output of that could be changed to be valid markdown?

**Comment by nschonni** [comment]
Thanks, I think that was basically what I was thinking of. I'll see what it would take to get it into markdown

**Comment by nex3** [comment]
I think #1517 is probably a better way of doing this, since that doesn't require us to ensure that the generated Markdown stays up-to-date with the tests.
