### ISSUE TITLE
"--output-style unspecified" doesn't seem to do anything

### ISSUE THREAD

**Issue by nex3** [sass/sass-spec#945]
`unspecified` is listed as a valid option for the `--output-style` flag, but it doesn't seem to actually change which tests are run. For example, `sass-spec.rb --output-style expanded spec/output_styles/compressed` runs tests, despite the options file specifying that they're compressed-mode.

**Comment by nschonni** [comment]
From https://github.com/sass/sass-spec/blob/master/lib/sass_spec/cli.rb#L86-L90 I think the `unspecified` is really just the same as saying "run everything". Not really sure what the point of that one is.
Ignoring `expanded` sounds like a bug though.

**Comment by saper** [comment]
Looks like a patch introducing options.yml processing didn't take this option into account. I think this option is also used to generate output, so this should be done carefully.

**Comment by stof** [comment]
@nex3 this should be closed as all specs are now in expanded style since a long time anyway.
