### ISSUE TITLE
Add support for known failing specs

### ISSUE THREAD

**Issue by nex3** [sass/sass-spec#948]
Right now, if a new implementation wanted to start the process of becoming sass-spec-compatible, there's no way to distinguish between a spec that's ignored for that implementation because it hasn't yet been implemented, or one that's ignored for some other reason (for example, #946). This makes it difficult to iteratively add support for more and more specs over time, while still running the passing specs to guard against any regressions.

I suggest a per-implementation "known failing" status that asserts that a spec doesn't pass for some reason. I think it's probably better for it not to be explicit about the reason, since it will generally represent work that hasn't been done yet, where the distinction between incorrect output and an explicit error isn't relevant.

**Comment by nex3** [comment]
Looking more closely, I see `--run-todo` and `--probe-todo` flags, which sounds like what I'm talking about. But I don't see any way of generating todo tests using interactive mode. Should I retarget this issue to be about generating todos interactively?

**Comment by nschonni** [comment]
I think the only way to create the TODOs right now is https://github.com/sass/sass-spec/blob/master/spec.sh. #950 is probably a possible solution along with adding something to the CLI

**Comment by xzyfer** [comment]
> Looking more closely, I see --run-todo and --probe-todo flags, which sounds like what I'm talking about. 

You're correct.

>But I don't see any way of generating todo tests using interactive mode. Should I retarget this issue to be about generating todos interactively?

I would suggest so.

>spec.sh 

This is my personal work flow that got accidental committed. I've had a couple people mention it was useful for them so I've kept it around.

**Comment by nschonni** [comment]
Looks like there is an actual `ignore` https://github.com/sass/sass-spec/blob/master/lib/sass_spec/annotate/cli.rb#L106 although I don't think anything currently uses it
